### PR TITLE
feat(csrf) enable csrf token in other way than ruby's one

### PR DESCRIPTION
**Pull request by cpuy**
add two otpions
- upload-options-csrf-param  name of the hidden parameter added to the form
- upload-options-enable-csrf  enable csrf in a simpler manner than ruby's one by getting token in cookie

### CODE REVIEW

**Comment by redboul** [comment]
looks good to me, I will test it in studio then...

**Comment by redboul** [comment]
OK, it work as expected but the token is not validated in the TokenValidatorFilter...
It does not comes the [get csrf token from request parameter](bonitasoft/bonita-web-sp#128) PR.
Or is it...
The form sends the CSRF token as a request parameter but the request `Content-Type` is `multipart/form-data`.  
And this kind of encoding does not extract the request content as request params.  

The request body input stream needs to be read inside the filter and then resetted for the servlet to read it another time (which is not possible natively with inputstream).  
It would require to add something like [a resettable input stream](https://gist.github.com/calo81/2071634) inside the filter (IMHO, a bit too much)...

what do you think?

**Comment by redboul** [comment]
maybe we could check with  HttpServletRequest#getParts(). checkout http://stackoverflow.com/questions/3337056/convenient-way-to-parse-incoming-multipart-form-data-parameters-in-a-servlet

**Comment by cpuy** [comment]
Hi guess this discussion should be part of this PR https://github.com/bonitasoft/bonita-ui-designer-sp/pull/2067

**Comment by cpuy** [comment]
Which version of Bonita are you using for your tests ?
Do you get a 401 ?

Sound weird since I've tested it and that worked

**Pull request merged**
